CREATE TABLE IF NOT EXISTS users(id IDENTITY PRIMARY KEY,username VARCHAR(32),password VARCHAR(32));
CREATE TABLE IF NOT EXISTS series(id IDENTITY PRIMARY KEY,name VARCHAR(32),description VARCHAR(256),userRating FLOAT,network VARCHAR(16),status VARCHAR(16),runtime INTEGER);
CREATE TABLE IF NOT EXISTS genres(id INTEGER REFERENCES series(id),genre VARCHAR(16),UNIQUE(id, genre));